# permissions for end users to view microfrontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microfrontend-viewer-role
rules:
- apiGroups:
  - frontend.example.com
  resources:
  - microfrontends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frontend.example.com
  resources:
  - microfrontends/status
  verbs:
  - get
