# permissions for end users to edit microfrontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microfrontend-editor-role
rules:
- apiGroups:
  - frontend.example.com
  resources:
  - microfrontends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frontend.example.com
  resources:
  - microfrontends/status
  verbs:
  - get
