
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - frontend.example.com
  resources:
  - microfrontends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frontend.example.com
  resources:
  - microfrontends/status
  verbs:
  - get
  - patch
  - update
